debug = true
[database]
# This section deals with the database location and how to access it
# Please note that at the moment, we have support for only postgresqa.
# Example, if you are Batman, your config would be:
# hostname = "batcave.org"
# port = "5432"
# username = "batman"
# password = "somereallycomplicatedBatmanpassword"
hostname = "localhost"
port = "5432"
username = "aravinth"
password = ""
database_name = "authdevel"

[server]
# This section deals with the configuration of the actual server

cookie_secret = "Zae0OOxf^bOJ#zN^&k7VozgW&QAx%n02TQFXpRMG4cCU0xMzgu3dna@tQ9dvc&TlE6p*n#kXUdLZJCQsuODIV%r$@o4%770ePQB7m#dpV!optk01NpY0@615w5e2Br4d"
# The port at which you want authentication to listen to
# takes a number, choose from 1000-10000 if you dont know what you are doing
port = 5000
# enter your hostname, eg: example.com
host= "localhost" 
domain = "batsense.net"
allow_registration = true
# when true, usernames containing unparliamentary words are filtered out
profainity_filter = true



[password_difficulty]
# WARNING: For advance users only, please don't touch this if you don't know what you are
# doing. You could significantly weaken the security of your passwords should you
# misconfigure this section
mem_cost= 656
time_cost= 5
hash_length= 32


